CREATE TABLE "tenants" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "name" varchar(255) NOT NULL,
  "slug" varchar(255) UNIQUE NOT NULL,
  "domain" varchar(255) UNIQUE,
  "status" varchar(20) NOT NULL DEFAULT 'active',
  "plan" varchar(20) NOT NULL DEFAULT 'free',
  "settings" jsonb,
  "ai_quota_monthly" int DEFAULT 1000,
  "ai_usage_current" int DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "full_name" varchar(255),
  "role" varchar(20) NOT NULL DEFAULT 'viewer',
  "status" varchar(20) NOT NULL DEFAULT 'active',
  "avatar_url" varchar(500),
  "bio" text,
  "skill_level" varchar(20) DEFAULT 'beginner',
  "learning_goals" jsonb,
  "ai_preferences" jsonb,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "parent_id" int,
  "slug" varchar(255) UNIQUE NOT NULL,
  "label" varchar(255) NOT NULL,
  "description" text,
  "icon" varchar(100),
  "color" varchar(50),
  "embedding" vector(1536),
  "created_by" int,
  "status" varchar(20) NOT NULL DEFAULT 'approved',
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "title" varchar(500) NOT NULL,
  "slug" varchar(500) UNIQUE NOT NULL,
  "summary" text,
  "content" text NOT NULL,
  "content_embedding" vector(1536),
  "thumbnail_url" varchar(500),
  "category_id" int,
  "sub_category_id" int,
  "status" varchar(20) NOT NULL DEFAULT 'draft',
  "is_featured" boolean DEFAULT false,
  "quality_score" decimal(3,2),
  "readability_score" decimal(3,2),
  "created_by" int,
  "view_count" int DEFAULT 0,
  "read_time" int DEFAULT 0,
  "like_count" int DEFAULT 0,
  "published_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "post_versions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int,
  "version_no" int NOT NULL,
  "title" varchar(500),
  "content" text,
  "edited_by" int,
  "change_note" text,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" int,
  "name" varchar(100) UNIQUE NOT NULL,
  "slug" varchar(100) UNIQUE NOT NULL,
  "usage_count" int DEFAULT 0,
  "embedding" vector(1536),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "post_tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int,
  "tag_id" int,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "post_id" int,
  "user_id" int,
  "parent_id" int,
  "content" text NOT NULL,
  "status" varchar(20) DEFAULT 'pending',
  "toxicity_score" decimal(3,2),
  "like_count" int DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "discussions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "user_id" int,
  "category_id" int,
  "title" varchar(500) NOT NULL,
  "slug" varchar(500) UNIQUE NOT NULL,
  "content" text NOT NULL,
  "content_embedding" vector(1536),
  "status" varchar(20) DEFAULT 'open',
  "upvote_count" int DEFAULT 0,
  "view_count" int DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "discussion_replies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "discussion_id" int,
  "user_id" int,
  "parent_id" int,
  "content" text NOT NULL,
  "upvote_count" int DEFAULT 0,
  "is_solution" boolean DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "likes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "likeable_type" varchar(50) NOT NULL,
  "likeable_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "follows" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "follower_id" int,
  "following_id" int,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "type" varchar(50) NOT NULL,
  "title" varchar(255) NOT NULL,
  "message" text,
  "link" varchar(500),
  "is_read" boolean DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "title" varchar(500) NOT NULL,
  "slug" varchar(500) UNIQUE NOT NULL,
  "description" text,
  "content_embedding" vector(1536),
  "level" varchar(20) NOT NULL,
  "topic" varchar(100),
  "duration_hours" int,
  "rating" decimal(3,2),
  "students_count" int DEFAULT 0,
  "price" varchar(50),
  "instructor_id" int,
  "status" varchar(20) DEFAULT 'published',
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "course_modules" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int,
  "title" varchar(255) NOT NULL,
  "description" text,
  "order_no" int NOT NULL,
  "content" text,
  "video_url" varchar(500),
  "duration_minutes" int,
  "is_free" boolean DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "course_enrollments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int,
  "user_id" int,
  "progress" int DEFAULT 0,
  "completed_modules" jsonb,
  "started_at" timestamp NOT NULL DEFAULT (now()),
  "completed_at" timestamp
);

CREATE TABLE "cheatsheets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "title" varchar(500) NOT NULL,
  "slug" varchar(500) UNIQUE NOT NULL,
  "description" text,
  "category" varchar(100),
  "downloads_count" int DEFAULT 0,
  "created_by" int,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "learning_paths" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "user_id" int,
  "title" varchar(255) NOT NULL,
  "description" text,
  "skill_level" varchar(20),
  "recommended_courses" jsonb,
  "progress" int DEFAULT 0,
  "ai_generated" boolean DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "certifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "user_id" int,
  "course_id" int,
  "certificate_url" varchar(500),
  "issued_at" timestamp NOT NULL DEFAULT (now()),
  "expires_at" timestamp
);

CREATE TABLE "competitions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "title" varchar(500) NOT NULL,
  "slug" varchar(500) UNIQUE NOT NULL,
  "description" text,
  "rules" text,
  "prize_pool" varchar(100),
  "difficulty" varchar(20),
  "category" varchar(100),
  "start_date" timestamp NOT NULL,
  "end_date" timestamp NOT NULL,
  "status" varchar(20) DEFAULT 'upcoming',
  "participants_count" int DEFAULT 0,
  "submissions_count" int DEFAULT 0,
  "created_by" int,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "competition_participants" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "competition_id" int,
  "user_id" int,
  "team_name" varchar(255),
  "registered_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "competition_submissions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "competition_id" int,
  "user_id" int,
  "code" text NOT NULL,
  "language" varchar(50),
  "score" decimal(10,4),
  "execution_time" int,
  "memory_used" int,
  "status" varchar(20) DEFAULT 'pending',
  "submitted_at" timestamp NOT NULL DEFAULT (now()),
  "evaluated_at" timestamp
);

CREATE TABLE "competition_leaderboards" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "competition_id" int,
  "user_id" int,
  "rank" int NOT NULL,
  "score" decimal(10,4) NOT NULL,
  "submissions_count" int DEFAULT 0,
  "last_submission_at" timestamp
);

CREATE TABLE "competition_test_cases" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "competition_id" int,
  "input" text NOT NULL,
  "expected_output" text NOT NULL,
  "is_public" boolean DEFAULT false,
  "weight" decimal(3,2) DEFAULT 1
);

CREATE TABLE "coding_challenges" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "title" varchar(500) NOT NULL,
  "slug" varchar(500) UNIQUE NOT NULL,
  "description" text,
  "difficulty" varchar(20) NOT NULL,
  "category" varchar(100),
  "tags" jsonb,
  "solution_template" text,
  "test_cases" jsonb,
  "acceptance_rate" decimal(5,2),
  "submissions_count" int DEFAULT 0,
  "created_by" int,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "challenge_submissions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "challenge_id" int,
  "user_id" int,
  "code" text NOT NULL,
  "language" varchar(50),
  "status" varchar(20),
  "execution_time" int,
  "memory_used" int,
  "submitted_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "datasets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "user_id" int,
  "title" varchar(500) NOT NULL,
  "slug" varchar(500) UNIQUE NOT NULL,
  "description" text,
  "category" varchar(100),
  "size_bytes" bigint,
  "file_format" varchar(50),
  "download_url" varchar(500),
  "license" varchar(100),
  "downloads_count" int DEFAULT 0,
  "upvote_count" int DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "models" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "user_id" int,
  "title" varchar(500) NOT NULL,
  "slug" varchar(500) UNIQUE NOT NULL,
  "description" text,
  "model_type" varchar(100),
  "framework" varchar(50),
  "download_url" varchar(500),
  "downloads_count" int DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "jobs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "company_name" varchar(255) NOT NULL,
  "title" varchar(500) NOT NULL,
  "slug" varchar(500) UNIQUE NOT NULL,
  "description" text,
  "requirements" text,
  "location" varchar(255),
  "remote" boolean DEFAULT false,
  "salary_range" varchar(100),
  "employment_type" varchar(50),
  "experience_level" varchar(50),
  "skills_required" jsonb,
  "applications_count" int DEFAULT 0,
  "status" varchar(20) DEFAULT 'active',
  "posted_by" int,
  "posted_at" timestamp NOT NULL DEFAULT (now()),
  "expires_at" timestamp
);

CREATE TABLE "job_applications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" int,
  "user_id" int,
  "resume_url" varchar(500),
  "cover_letter" text,
  "status" varchar(20) DEFAULT 'pending',
  "applied_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "portfolios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "user_id" int,
  "title" varchar(255),
  "bio" text,
  "website_url" varchar(500),
  "github_url" varchar(500),
  "linkedin_url" varchar(500),
  "resume_url" varchar(500),
  "is_public" boolean DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "projects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "user_id" int,
  "title" varchar(500) NOT NULL,
  "slug" varchar(500) UNIQUE NOT NULL,
  "description" text,
  "github_url" varchar(500),
  "demo_url" varchar(500),
  "tech_stack" jsonb,
  "upvote_count" int DEFAULT 0,
  "view_count" int DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "user_skills" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "skill_name" varchar(100) NOT NULL,
  "proficiency" varchar(20),
  "years_experience" int,
  "verified" boolean DEFAULT false
);

CREATE TABLE "newsletters" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "title" varchar(255) NOT NULL,
  "content" text NOT NULL,
  "status" varchar(20) DEFAULT 'draft',
  "scheduled_at" timestamp,
  "sent_at" timestamp,
  "recipients_count" int DEFAULT 0,
  "open_rate" decimal(5,2),
  "click_rate" decimal(5,2),
  "created_by" int,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "newsletter_subscriptions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "email" varchar(255) NOT NULL,
  "subscribed" boolean DEFAULT true,
  "subscribed_at" timestamp NOT NULL DEFAULT (now()),
  "unsubscribed_at" timestamp
);

CREATE TABLE "support_tickets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "user_id" int,
  "subject" varchar(500) NOT NULL,
  "message" text NOT NULL,
  "status" varchar(20) DEFAULT 'open',
  "priority" varchar(20) DEFAULT 'medium',
  "category" varchar(50) NOT NULL,
  "assigned_to" int,
  "ai_suggested_solution" text,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "support_ticket_replies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_id" int,
  "user_id" int,
  "message" text NOT NULL,
  "is_staff" boolean DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "moderation_strategies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" int,
  "name" varchar(255) NOT NULL,
  "type" varchar(50) NOT NULL,
  "enabled" boolean DEFAULT true,
  "config" jsonb NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "ai_conversations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "user_id" int,
  "tenant_id" int,
  "title" varchar(255),
  "context_type" varchar(50),
  "context_id" int,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "ai_messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" int,
  "role" varchar(20) NOT NULL,
  "content" text NOT NULL,
  "tokens_used" int,
  "model" varchar(50),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "ai_code_reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "user_id" int,
  "code_snippet" text NOT NULL,
  "language" varchar(20) DEFAULT 'go',
  "review_result" jsonb,
  "suggestions" jsonb,
  "quality_score" decimal(3,2),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "content_recommendations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "content_type" varchar(50) NOT NULL,
  "content_id" int NOT NULL,
  "score" decimal(3,2),
  "reason" varchar(255),
  "shown_at" timestamp,
  "clicked" boolean DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "post_views" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int,
  "user_id" int,
  "ip_address" varchar(45),
  "user_agent" text,
  "referrer" varchar(500),
  "time_spent_seconds" int,
  "viewed_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "tenant_stats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" int,
  "date" date NOT NULL,
  "total_users" int DEFAULT 0,
  "total_posts" int DEFAULT 0,
  "total_views" int DEFAULT 0,
  "ai_queries_count" int DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "activity_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "tenant_id" int,
  "action" varchar(100) NOT NULL,
  "entity_type" varchar(50) NOT NULL,
  "entity_id" int NOT NULL,
  "metadata" jsonb,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "media_files" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid UNIQUE NOT NULL,
  "tenant_id" int,
  "user_id" int,
  "filename" varchar(500) NOT NULL,
  "file_path" varchar(1000) NOT NULL,
  "file_url" varchar(1000) NOT NULL,
  "mime_type" varchar(100) NOT NULL,
  "file_size" bigint NOT NULL,
  "width" int,
  "height" int,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "search_index" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" int,
  "searchable_type" varchar(50) NOT NULL,
  "searchable_id" int NOT NULL,
  "title" varchar(500) NOT NULL,
  "content" text NOT NULL,
  "search_vector" tsvector,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE INDEX ON "tenants" ("slug");

CREATE INDEX ON "tenants" ("domain");

CREATE INDEX ON "tenants" ("status");

CREATE INDEX ON "users" ("email");

CREATE INDEX ON "users" ("username");

CREATE INDEX ON "users" ("tenant_id");

CREATE INDEX ON "categories" ("slug");

CREATE INDEX ON "categories" ("tenant_id");

CREATE INDEX ON "categories" USING IVFFLAT ("embedding");

CREATE INDEX ON "posts" ("slug");

CREATE INDEX ON "posts" ("category_id");

CREATE INDEX ON "posts" ("tenant_id");

CREATE INDEX ON "posts" ("status");

CREATE INDEX ON "posts" USING IVFFLAT ("content_embedding");

CREATE UNIQUE INDEX ON "post_versions" ("post_id", "version_no");

CREATE INDEX ON "tags" ("slug");

CREATE INDEX ON "tags" USING IVFFLAT ("embedding");

CREATE UNIQUE INDEX ON "post_tags" ("post_id", "tag_id");

CREATE INDEX ON "comments" ("post_id");

CREATE INDEX ON "comments" ("user_id");

CREATE INDEX ON "comments" ("status");

CREATE INDEX ON "discussions" ("slug");

CREATE INDEX ON "discussions" ("user_id");

CREATE INDEX ON "discussions" ("status");

CREATE INDEX ON "discussions" USING IVFFLAT ("content_embedding");

CREATE INDEX ON "discussion_replies" ("discussion_id");

CREATE INDEX ON "discussion_replies" ("user_id");

CREATE UNIQUE INDEX ON "likes" ("user_id", "likeable_type", "likeable_id");

CREATE UNIQUE INDEX ON "follows" ("follower_id", "following_id");

CREATE INDEX ON "notifications" ("user_id");

CREATE INDEX ON "notifications" ("is_read");

CREATE INDEX ON "courses" ("slug");

CREATE INDEX ON "courses" ("level");

CREATE INDEX ON "courses" USING IVFFLAT ("content_embedding");

CREATE INDEX ON "course_modules" ("course_id", "order_no");

CREATE UNIQUE INDEX ON "course_enrollments" ("user_id", "course_id");

CREATE INDEX ON "course_enrollments" ("course_id");

CREATE INDEX ON "cheatsheets" ("slug");

CREATE INDEX ON "cheatsheets" ("category");

CREATE INDEX ON "learning_paths" ("user_id");

CREATE INDEX ON "certifications" ("user_id");

CREATE INDEX ON "certifications" ("course_id");

CREATE INDEX ON "competitions" ("slug");

CREATE INDEX ON "competitions" ("status");

CREATE INDEX ON "competitions" ("start_date");

CREATE UNIQUE INDEX ON "competition_participants" ("competition_id", "user_id");

CREATE INDEX ON "competition_participants" ("competition_id");

CREATE INDEX ON "competition_submissions" ("competition_id");

CREATE INDEX ON "competition_submissions" ("user_id");

CREATE INDEX ON "competition_submissions" ("score");

CREATE INDEX ON "competition_leaderboards" ("competition_id", "rank");

CREATE UNIQUE INDEX ON "competition_leaderboards" ("competition_id", "user_id");

CREATE INDEX ON "competition_test_cases" ("competition_id");

CREATE INDEX ON "coding_challenges" ("slug");

CREATE INDEX ON "coding_challenges" ("difficulty");

CREATE INDEX ON "coding_challenges" ("category");

CREATE INDEX ON "challenge_submissions" ("challenge_id");

CREATE INDEX ON "challenge_submissions" ("user_id");

CREATE INDEX ON "datasets" ("slug");

CREATE INDEX ON "datasets" ("category");

CREATE INDEX ON "datasets" ("user_id");

CREATE INDEX ON "models" ("slug");

CREATE INDEX ON "models" ("model_type");

CREATE INDEX ON "jobs" ("slug");

CREATE INDEX ON "jobs" ("status");

CREATE INDEX ON "jobs" ("posted_at");

CREATE UNIQUE INDEX ON "job_applications" ("job_id", "user_id");

CREATE INDEX ON "job_applications" ("user_id");

CREATE UNIQUE INDEX ON "portfolios" ("user_id");

CREATE INDEX ON "projects" ("slug");

CREATE INDEX ON "projects" ("user_id");

CREATE UNIQUE INDEX ON "user_skills" ("user_id", "skill_name");

CREATE INDEX ON "user_skills" ("user_id");

CREATE INDEX ON "newsletters" ("tenant_id");

CREATE INDEX ON "newsletters" ("status");

CREATE UNIQUE INDEX ON "newsletter_subscriptions" ("email");

CREATE INDEX ON "newsletter_subscriptions" ("user_id");

CREATE INDEX ON "support_tickets" ("user_id");

CREATE INDEX ON "support_tickets" ("status");

CREATE INDEX ON "support_tickets" ("assigned_to");

CREATE INDEX ON "support_ticket_replies" ("ticket_id");

CREATE INDEX ON "moderation_strategies" ("tenant_id");

CREATE INDEX ON "moderation_strategies" ("type");

CREATE INDEX ON "ai_conversations" ("user_id");

CREATE INDEX ON "ai_conversations" ("tenant_id");

CREATE INDEX ON "ai_messages" ("conversation_id");

CREATE INDEX ON "ai_code_reviews" ("user_id");

CREATE INDEX ON "content_recommendations" ("user_id");

CREATE INDEX ON "content_recommendations" ("content_type", "content_id");

CREATE INDEX ON "post_views" ("post_id");

CREATE INDEX ON "post_views" ("user_id");

CREATE INDEX ON "post_views" ("viewed_at");

CREATE UNIQUE INDEX ON "tenant_stats" ("tenant_id", "date");

CREATE INDEX ON "activity_logs" ("user_id");

CREATE INDEX ON "activity_logs" ("tenant_id");

CREATE INDEX ON "activity_logs" ("entity_type", "entity_id");

CREATE INDEX ON "media_files" ("user_id");

CREATE INDEX ON "media_files" ("tenant_id");

CREATE INDEX ON "search_index" ("tenant_id");

CREATE UNIQUE INDEX ON "search_index" ("searchable_type", "searchable_id");

CREATE INDEX ON "search_index" USING GIN ("search_vector");

ALTER TABLE "users" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "categories" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "categories" ADD FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "categories" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "posts" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "posts" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "posts" ADD FOREIGN KEY ("sub_category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "posts" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_versions" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_versions" ADD FOREIGN KEY ("edited_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tags" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_tags" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("parent_id") REFERENCES "comments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discussions" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discussions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discussions" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discussion_replies" ADD FOREIGN KEY ("discussion_id") REFERENCES "discussions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discussion_replies" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discussion_replies" ADD FOREIGN KEY ("parent_id") REFERENCES "discussion_replies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "follows" ADD FOREIGN KEY ("follower_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "follows" ADD FOREIGN KEY ("following_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "courses" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "courses" ADD FOREIGN KEY ("instructor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_modules" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_enrollments" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_enrollments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cheatsheets" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cheatsheets" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "learning_paths" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "certifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "certifications" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competitions" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competitions" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competition_participants" ADD FOREIGN KEY ("competition_id") REFERENCES "competitions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competition_participants" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competition_submissions" ADD FOREIGN KEY ("competition_id") REFERENCES "competitions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competition_submissions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competition_leaderboards" ADD FOREIGN KEY ("competition_id") REFERENCES "competitions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competition_leaderboards" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competition_test_cases" ADD FOREIGN KEY ("competition_id") REFERENCES "competitions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "coding_challenges" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "coding_challenges" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "challenge_submissions" ADD FOREIGN KEY ("challenge_id") REFERENCES "coding_challenges" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "challenge_submissions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "datasets" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "datasets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "models" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "models" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "jobs" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "jobs" ADD FOREIGN KEY ("posted_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "job_applications" ADD FOREIGN KEY ("job_id") REFERENCES "jobs" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "job_applications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "portfolios" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projects" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projects" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_skills" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "newsletters" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "newsletters" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "newsletter_subscriptions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "support_tickets" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "support_tickets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "support_tickets" ADD FOREIGN KEY ("assigned_to") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "support_ticket_replies" ADD FOREIGN KEY ("ticket_id") REFERENCES "support_tickets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "support_ticket_replies" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "moderation_strategies" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ai_conversations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ai_conversations" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ai_messages" ADD FOREIGN KEY ("conversation_id") REFERENCES "ai_conversations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ai_code_reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "content_recommendations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_views" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_views" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tenant_stats" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "activity_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "activity_logs" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "media_files" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "media_files" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "search_index" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;
